### ISSUE TITLE
Headlamp Icons does not load in isolated environment.

### ISSUE THREAD

**Issue by jgyy** [headlamp-k8s/headlamp#1103]
I am trying to host headlamp in cluster on an isolated environment without internet access. However the frontend dashboard is trying to load the following icons from the internet (links below) which will not work at all if I am accessing the dashboard from an isolated environment without internet access.

Can somebody look into it and make the icons load as assets locally instead of trying to fetch a public icon?  Not just icons, any other public CDN will not work in isolated environment. Thanks!

https://api.iconify.design/mdi.json
https://api.simplesvg.com/mdi.json
https://api.unisvg.com/mdi.json

**Comment by illume** [comment]
Hello.There are a number of fixes for this merged into main. We are going to do another release this week (hopefully).best regards,On 25. Apr 2023, at 10:33, jgyy ***@***.***> wrote:﻿
I am trying to host headlamp in cluster on an isolated environment without internet access. However the frontend dashboard is trying to load the following icons from the internet (links below) which will not work at all if I am accessing the dashboard from an isolated environment without internet access.
Can somebody look into it and make the icons load as assets locally instead of trying to fetch a public icon?  Not just icons, any other public CDN will not work in isolated environment. Thanks!
https://api.iconify.design/mdi.json
https://api.simplesvg.com/mdi.json
https://api.unisvg.com/mdi.json

**Comment by jgyy** [comment]
I hope the list of fixes also includes having local icon assets though. thanks anyway

**Comment by joaquimrocha** [comment]
@jgyy , thanks. Closing this as it should be now available as mentioned.
If you spot any missing icon, please let us know. We will also work on a way to detect any missing icons from the cache in #1109 .
