### ISSUE TITLE
Allow to set up dynamic clusters safely in a shared environment

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1249]
Right now we do not enable the dynamic clusters feature except in a non-shared environment (desktop) but we'd like to do so since some may deploy Headlamp as a web service but would like users to be able to set up clusters individually, through a plugin for example.
The problem with allowing this feature is a shared environment is that, since we do not have an authentication system coupled with headlamp (auth is handled by the API server), any added clusters would be visible to all users; it'd also allow for denial of service abuse since one could just keep pushing new clusters.

So we should investigate if there's a way to do this safely while avoiding having to have a user authentication coupled with headlamp itself.

Some suggestions for this include:
1. Keeping the cluster info local (client-side/browser) and always passing the cluster info on every request. Caveats: too much data on every request, and/or insuficient data dependending on how the cluster is to be configured.
2. Using an associated session ID so users only see the clusters set up for their session. Caveats: would not prevent DOS attacks.

**Comment by knrt10** [comment]
Looking more into this

**Comment by knrt10** [comment]
I looked more into this, sharing my findings.

### Regarding 1st approach.
- Instead of passing **all cluster** info on every request, we should consider passing a _unique cluster_ identifier or a minimal set of necessary information for each request. This way, we can reduce the data size while still allowing Headlamp to fetch specific cluster details as needed.
- We already have caching in headlamp, we can leverage that and use client-side caching to reduce the number of requests for cluster information. Store the cluster details locally on the client-side so that repeated requests for the same cluster can be served from the cache, reducing the amount of data transmitted over the network.

### Regarding second approach.
- To prevent DoS attacks, we can combine the associated session ID with rate-limiting mechanisms. This way, even if a user's session allows them to set up multiple clusters, they are still subject to rate limits to prevent excessive cluster creation in a short period.
- We can Implement a session expiration mechanism to ensure that unused or inactive sessions are cleared after a certain period of inactivity, freeing up resources and preventing abandoned sessions from cluttering the system.

### More suggestions

#### Namespace Isolation(To be done by user):

In Kubernetes, we can utilize namespaces to provide isolation for each user's clusters. When a user creates a new cluster, it should be created within their designated namespace. This way, each user's clusters remain isolated from one another, and they can only see and manage their own clusters. Then user can create service account will required RBAC on who can access that namespace resources.

#### Dynamic Cluster Provisioning(Headlamp does this):

Implement a Kubernetes custom controller or operator within Headlamp to handle dynamic cluster provisioning. When a user requests a new cluster, the controller creates a new namespace for the user and provisions the cluster within that namespace. This controller can also ensure that the controller enforces cluster quotas per user to prevent any single user from creating an excessive number of clusters.

#### Rate Limiting and Resource Quotas(Headlamp does this):

We can leverage Kubernetes built-in rate limiting and resource quota mechanisms. Set appropriate limits on cluster creation and resource usage to prevent DoS attacks and resource abuse in the shared environment. The Kubernetes API server can enforce these limits for each user and namespace, ensuring that users can only create clusters according to their allocated resources and rate limits.
