### ISSUE TITLE
Home View: Cannot access API properly 

### ISSUE THREAD

**Issue by Alepernicolo** [headlamp-k8s/headlamp#1459]
Hey everyone, I have been wanting to edit the home view ([issue 1397](https://github.com/headlamp-k8s/headlamp/issues/1397)), specifically the table and thankfully I can do that now.

I now want to add a column that has specific data contained in a config map from a specific namespace (e.g. _alpha_). Unfortunately the documentation is a bit sparse and could not help. I have been trying everything going through the  ConfigMap and Namespace scripts. Could it be that I cannot access cluster specific properties from within the home view?

**Comment by joaquimrocha** [comment]
@Alepernicolo , the Home view is relatively new and our API for handling cluster resources assumes that you are in a cluster context for it to pick it up. However, we have a POC (is already a few months old) for using the cluster as an argument for any resource functions, in the [aggregated-view](https://github.com/headlamp-k8s/headlamp/tree/aggregated-view) branch.
We will soon take on that POC and improve it, so that will unblock this functionality. We may work on the functionality of passing the cluster as an arg to those functions even before we finish the aggregated cluster view, so please allow us some time.

**Comment by Alepernicolo** [comment]
Thanks for clarifying and your efforts. Of course, take your time.

**Comment by illume** [comment]
This is done in #1747
