### ISSUE TITLE
Bug: Deletion in the wrong cluster through delay

### ISSUE THREAD

**Issue by farodin91** [headlamp-k8s/headlamp#1660]
Reproduce:
1.  click on delete secret
2. switch to different cluster which has a secret with the same namespace and name
3. wait for delay to end
4. secret in switched cluster is gone

**Comment by yolossn** [comment]
Hey @farodin91 thanks for bringing this to notice. May I know how long is the delay?

**Comment by joaquimrocha** [comment]
Oh damn. The delay doesn't really matter. I guess the problem is that we fetch the current cluster at the end of the delay, and if that has changed, then it'll use the different cluster 😵‍💫 

We can add a way to prevent this right now (make it fail the deletion if the cluster was changed) until we have #1591 merged in as the latter is needed for a proper fix.
