### ISSUE TITLE
[RFE] Customizable columns in various list views (pods, nodes, etc.)

### ISSUE THREAD

**Issue by yanrez** [headlamp-k8s/headlamp#366]
## Current situation

Currently list of pods or nodes shows predefined set of columns:
- Pods show name, namespace, restarts, status and age.
- Nodes show name, readiness, cpu, memory and age.

These lists missing other information that can be very useful in overall summary in various situations. For example, user can't see nodes uptime or pod's node placement in overall list and has to click on each item to check.
Similar statement can be done for other resource types.

## Impact

Lack of important information makes it harder to assess state of overall state of cluster and see patterns without resorting to kubectl.

## Ideal future situation

Being able to add/remove/rearrange columns in the list views, and filter by custom columns will help a lot in analyzing the overall status. Have a broader list of supported columns, that can be added/removed from views, as well as ability to memorize those per view will be very useful.

**Comment by joaquimrocha** [comment]
Thanks @yanrez , this is very interesting (and challenging) from a UI point of view.
This can of course already be accomplished by using plugins, but it's a lot of repeated work to be able to offer that, so we will explore whether we can offer something lighter.

**Comment by joaquimrocha** [comment]
Adding to the roadmap as proposed. I think adding a feature like add/remove/rearrange columns can be a good thing for increasing the adoption and is very in line with what we created Headlamp for.

**Comment by illume** [comment]
> For example, user can't see nodes uptime or pod's node placement in overall list and has to click on each item to check.

I wanted to add a note about...
How can you see extra data with kubectl, and how can that translate into what Headlamp does in a browser?

1) "-o wide" kubectl option
2) [custom column](https://kubernetes.io/docs/reference/kubectl/#custom-columns) kubectl options.
3) responsively showing different columns based on browser window width


## 1) "-o wide" option

Terminal windows are 80x24 (because olden days) by default usually.
So not so much information can fit by default.
The popular kubectl "-o wide" option lets you fill up your big terminal window.

@fondoger already made a patch with a toggle UI to switch between wide column mode and back. In a way this is toggling custom fields too. The wide format toggle is a low interaction way of showing extra fields that you don't need to specify manually.


```bash
$ kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS              RESTARTS       AGE
headlamp      headlamp-866f5bd7bc-fvx7s          1/1     Running             0              2d8h
kube-system   coredns-6d4b75cb6d-6qppl           1/1     Running             0              4d21h
kube-system   etcd-minikube                      1/1     Running             0              4d21h
kube-system   headlamp-67bd796b7b-7vgrh          0/1     ErrImageNeverPull   0              4d21h
kube-system   kube-apiserver-minikube            1/1     Running             0              4d21h
kube-system   kube-controller-manager-minikube   1/1     Running             0              4d21h
kube-system   kube-proxy-bsz7s                   1/1     Running             0              4d21h
kube-system   kube-scheduler-minikube            1/1     Running             0              4d21h
kube-system   storage-provisioner                1/1     Running             2 (3d7h ago)   4d21h


$ kubectl get pods -A -o wide
NAMESPACE     NAME                               READY   STATUS              RESTARTS       AGE     IP             NODE       NOMINATED NODE   READINESS GATES
headlamp      headlamp-866f5bd7bc-fvx7s          1/1     Running             0              2d8h    172.17.0.4     minikube   <none>           <none>
kube-system   coredns-6d4b75cb6d-6qppl           1/1     Running             0              4d21h   172.17.0.2     minikube   <none>           <none>
kube-system   etcd-minikube                      1/1     Running             0              4d21h   192.168.49.2   minikube   <none>           <none>
kube-system   headlamp-67bd796b7b-7vgrh          0/1     ErrImageNeverPull   0              4d21h   172.17.0.3     minikube   <none>           <none>
kube-system   kube-apiserver-minikube            1/1     Running             0              4d21h   192.168.49.2   minikube   <none>           <none>
kube-system   kube-controller-manager-minikube   1/1     Running             0              4d21h   192.168.49.2   minikube   <none>           <none>
kube-system   kube-proxy-bsz7s                   1/1     Running             0              4d21h   192.168.49.2   minikube   <none>           <none>
kube-system   kube-scheduler-minikube            1/1     Running             0              4d21h   192.168.49.2   minikube   <none>           <none>
kube-system   storage-provisioner                1/1     Running             2 (3d7h ago)   4d21h   192.168.49.2   minikube   <none>           <none>
```

## 2) [custom column](https://kubernetes.io/docs/reference/kubectl/#custom-columns) kubectl options.

Here we see kubectl allows not only specifying the data to show in the columns, but also the column names.

```bash
kubectl get pod -o custom-columns="POD-NAME":.metadata.name,"NAMESPACE":.metadata.namespace,"CONTAINER-IMAGES":.spec.containers[*].image -A
POD-NAME                           NAMESPACE     CONTAINER-IMAGES
headlamp-866f5bd7bc-fvx7s          headlamp      ghcr.io/kinvolk/headlamp:v0.9.0@sha256:465aaee6518f3fdd032965eccd6a8f49e924d144b1c86115bad613872672ec02
coredns-6d4b75cb6d-6qppl           kube-system   k8s.gcr.io/coredns/coredns:v1.8.6
etcd-minikube                      kube-system   k8s.gcr.io/etcd:3.5.3-0
headlamp-67bd796b7b-7vgrh          kube-system   ghcr.io/kinvolk/headlamp:latest
kube-apiserver-minikube            kube-system   k8s.gcr.io/kube-apiserver:v1.24.3
kube-controller-manager-minikube   kube-system   k8s.gcr.io/kube-controller-manager:v1.24.3
kube-proxy-bsz7s                   kube-system   k8s.gcr.io/kube-proxy:v1.24.3
kube-scheduler-minikube            kube-system   k8s.gcr.io/kube-scheduler:v1.24.3
storage-provisioner                kube-system   gcr.io/k8s-minikube/storage-provisioner:v5

```

## 3) responsively showing different columns based on browser window width

Here we show a fairly wide browser window. More columns can easily fit in there.

![image](https://user-images.githubusercontent.com/9541/197987601-4c53bb17-f0aa-4956-aaed-06191a039802.png)

With a wide browser window, why not show a wide set of data? Information overflow is one reason. The most important information should usually be shown, and more information on the screen makes it harder for that information to stand out.

**Comment by yanrez** [comment]
I totally agree it is important to be careful when choosing what columns are visible by default. I argue for need for user to be able to customize set of columns, as well as improving current defaults for wider screens. 
I would note that screenshot shows a very sparse representation - columns and rows have overly big spacing a between them. There should be some density on the screen to make user efficient in consuming data.
There are ways to make important information standing out without making view too sparse.

**Comment by lijianzhi01** [comment]
It will be great to add an operation column. Our customers told us that it will be efficient to quickly perform actions in Pod/Deployment list. Such like this.
![image](https://user-images.githubusercontent.com/13809749/198179256-f6037849-a892-4a9b-a2fe-3939f7a88856.png)

**Comment by lijianzhi01** [comment]
I think columns should be configured through plugin. 
Defned in our product
![image](https://user-images.githubusercontent.com/13809749/198229114-da2d354d-864b-40f4-b1d8-bc42369b5fbe.png)

Headlamp
![image](https://user-images.githubusercontent.com/13809749/198229335-82184510-01f1-44f0-9566-aa5259fa4222.png)

**Comment by illume** [comment]
> I totally agree it is important to be careful when choosing what columns are visible by default. I argue for need for user to be able to customize set of columns, as well as improving current defaults for wider screens.

Yes, I think both of these are important as well.

> I would note that screenshot shows a very sparse representation - columns and rows have overly big spacing a between them. There should be some density on the screen to make user efficient in consuming data. There are ways to make important information standing out without making view too sparse.

Yeah, having table data densely packed might be a good idea to show when there are lots of extra custom columns.

About table spacing and density, I see a few possibilities:
1) have a user preference to select density
2) show all tables densely packed (using lines to separate data, rather than plenty of space).
3) responsively show data as densely packed when there are lots of columns (more than will fit in the browser width)

**Comment by joaquimrocha** [comment]
I forgot to reply to this.
I like the idea of having the columns be shown depending on the space they have available. However, it still begs the question of which columns to show by default, and even with the responsive approach, it's impossible to show them all, so the user may want to have some shown and others hidden.

A binary choice (wide/cozy) may not be very flexible in this regard, so I see the wide/cozy as automatically done by the responsiveness (i.e. the width), but ultimately what I believe would please all users (based on the comments) would be a way to edit columns like some sections in the Azure Portal support.
![Screenshot showing the Edit Columns section of the Azure Portal](https://user-images.githubusercontent.com/1029635/203977552-69556d2d-fa2e-4771-b936-bfeb3f321cae.png)

Adding a way for plugins to modify the default columns would be great too.

**Comment by zzl221000** [comment]
> 添加操作列会很棒。我们的客户告诉我们，在 Pod/部署列表中快速执行操作会很有效。像这样。 ![image](https://user-images.githubusercontent.com/13809749/198179256-f6037849-a892-4a9b-a2fe-3939f7a88856.png)

I really want this feature so badly.

**Comment by lijianzhi01** [comment]
It seems like this topic recieved lots of attraction. I think the pain point here is how to make a design, which reduce the times of operation to find issue and mitigate. So, here is my suggestions:
1. Resource list table should add more columns, which are parsed from native k8s objects and self customized columns. Those columns are super useful for k8s scenarios. 
![image](https://github.com/headlamp-k8s/headlamp/assets/13809749/c841bc42-d570-4e44-8d8c-3ac096494005)

2. Resource list table should add operations columns. User simply don't want to delete or edit by click into detail page. Because lots of time it is not necessary.
![image](https://github.com/headlamp-k8s/headlamp/assets/13809749/b0fdc72e-5879-45ff-ac53-d19b411f322f)

3. Resource list table should add status filter, which should be very prominent. Typical scenario is like user wants to know crashing pods only, and then delete or exec.
![image](https://github.com/headlamp-k8s/headlamp/assets/13809749/c9b00a7e-cbc2-4a30-852c-63c5c18904db)

4. It would be great to open detail page besides list. Because users hate to lost just selected item. If jump back from detail page, user has to find just selected item. More time to spend on get recovered from other pages.
