### ISSUE TITLE
[RFE] Support authentication plugin to override getToken() and setToken()

### ISSUE THREAD

**Issue by lijianzhi01** [headlamp-k8s/headlamp#469]
## Current situation

Get or set token are either from oidc sign in or input token by user. 

1. Microsoft authentication will require redirect or popup. In desktop app situation, it is not supported. Organization might set redirect to http://localhost:xxxx/blank, but desktop app only cannot load that URL. You might use popup way to authenticate, but now it is not supported by Headlamp, too.
2. If token is expired, headlamp redirect to landing page. User lost their operation context. They might spend lots of time to find out what context they were after sign in again.

## Impact

1. Define authentication processes. No matter redirection, popup way, or any other ways, user can manage by themselves.
2. Token might be expired, sign in user immediately inside getToken() without break user's operation.

**Comment by illume** [comment]
We had some discussions on how to do this, the pros and cons of different approaches. I'll try to summarize that here.

### Flow for authentication using users browser.

1) open users browser at the auth page, including the URL for redirect to the backend server.exe `localhost:xxx/authreturn`
2) `localhost:xxx/authreturn` is open in the users browser, this will save the token inside the server.exe process so that it can be accessed by the Electron app.
3) The Headlamp electron app will then be able to take the token(by reading a route on the backend).
4) Headlamp can become the focused window (the active window on top of the browser window).

### Why not a popup within the Headlamp electron app? 

Doing auth in an electron Headlamp popup can be a security issue for a number of reasons and also be a worse experience. By default Electron blocks popups, so that layer of defense would need to be lowered ([there is an open PR to allow about:blank popups](https://github.com/kinvolk/headlamp/pull/470)).  One workaround for this problem would be to have an allowlist of domains to be trusted (to be managed somehow). However there are further issues. Having users type passwords into the app is not good, because passwords in general should be avoided. If a user uses their browser it can probably use the existing authentication infrastructure to avoid passwords. Finally, it is a better experience for the user to use their own (Edge) browser authentication they are used to that is able to authenticate with less friction and with perhaps more capabilities than what Electron (chromium based) supports.

@ashu8912 can you please look at the "Flow for authentication using users browser."

**Comment by lijianzhi01** [comment]
I think there are two things need to be clear.
### First, about [1]. 
I think Headlamp do not need to care about authentication, instead Headlamp need to provide an endpoint http://localhost:4466/blank for a temporarily use. This endpoint will do nothing but send 200 to client. Let me explain how we designed our authentication flow. Take popup as example. 
1. We designed landing page plugin. This plugin will launch authentication process with MSAL by window.open(), which is popup way. (Although, MSAL provides redirect MSAL, but **it will break user's operation that redirect to sign in page when access token expired.)** 
2. After user logon in, popup will redirect to http://localhost:4466/blank. At this moment, MSAL finds out popup's url is http://localhost:4466/blank, it will close popup and store account's info into cookie. link
3. Now, our plugin can get access token by MSAL. 
In this way, only two things Headlamp need to do. One is setup an endpoint, http://localhost:4466/blank. Second is allow us to overwrite getToken() and setToken(). In this way, we can get access by our method. And authenticate user without break operation context when access token is expired.

### Second is about popup.
Can headlamp open browser can be through window.open() inside MSAL? We do not care about open popup by electron window or edge window.

**Comment by illume** [comment]
> User do not input password in popup, they will be authenticated by physical key.

It's my understanding the electron app has a separate context than Edge. It asks the user to login more, and presents password based login because other authentication methods are not available to it. Did you already test the physical key auth works ok using the Electron app popup?

**Comment by joaquimrocha** [comment]
This is fixed now since #892 .
